[platformio]
src_dir = motion_monitor

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; upload_port = /dev/cu.usbserial-XXXX   ; Uncomment & set your serial port / 取消註解並改成你的序列埠
; monitor_port = /dev/cu.usbserial-XXXX  ; macOS: ls /dev/cu.* to find it / macOS 用 ls /dev/cu.* 查看
board_build.partitions = huge_app.csv
board_build.flash_mode = qio
lib_deps =
  knolleary/PubSubClient@^2.8
